=== ElodieFerreira/SpaceEnigmas/src/data/espace.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT espace (planete+)>
<!ELEMENT planete (nom,description,cartePlanete)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT cartePlanete (zone+)>
<!ELEMENT zone (nom,description,image,sortie+)>
<!ATTLIST zone index ID #REQUIRED>
<!ELEMENT image (#PCDATA)>
<!ELEMENT sortie (#PCDATA)>
<!ATTLIST sortie index ID #REQUIRED>

=== ElodieFerreira/SpaceEnigmas/bin/data/espace1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE espace SYSTEM "espace.dtd" >
<espace>
<!-- La sortie Index 0 correspond au vaisseau -->
  <planete>
    <nom>Perlimpinpin</nom>
    <description>Perlimpinpin est une planète isolée dans la galaxie. Ses habitants ne sont pas très importants.</description>
    <cartePlanete>
    	<zone index="1">
				<nom>Spatioport</nom>
				<description> Un spatioport peu fréquenté. Le seul moyen de sortir de la planète et de rejoindre le reste de la civilisation.</description>
				<image>spatioport.png</image>
				<sortie index="0">SUD</sortie>
				<sortie index="2">NORD</sortie>
		</zone>
		<zone index="2">
				<nom>Perlimpinpin : Marché</nom>
				<description> Un petit marché local où les habitants se réunissent pour acheter aux marchands voyageurs des produits de toute la galaxie. </description>
				<image>marcheSiGifOk.gif</image>
				<sortie index="1">SUD</sortie>
				<sortie index="3">OUEST</sortie>
		</zone>
		<zone index="3">
				<nom>Maison de joueur</nom>
				<description> Une chambre typique, d'une maison ordinaire, sur une plan�te sans histoire...</description>
				<image>Maisonjoueur.gif</image>
				<sortie index="2">EST</sortie>
		</zone>
    </cartePlanete>
  </planete>
  <planete>
    <nom>Samaria</nom>
    <description>Samaria est une planète agricole nourissant la majorité de la galaxie. Ses habitants ne semblent pas savoir qu'ils disposent de technologies ultra-avancées et préfèrent vivre une vie simple, comme dans les anciens temps.</description>
    <cartePlanete>
    	<zone index="4">
				<nom>Spatioport</nom>
				<description> Un spatioport très fréquenté par les marchands voyageurs qui y acheminent des denrées vers les plus grandes planètes. Les habitants de Samaria ne le visitent pas du tout.</description>
				<image>vaisseau.png</image>
				<sortie index="0">SUD</sortie>
				<sortie index="5">NORD</sortie>
		</zone>
		<zone index="5">
				<nom>Prairie isolée</nom>
				<description>Une petite prairie à l'écart de la planète. Les bergers y emmènent parfois leur troupeau. </description>
				<image>marcheSiGifOk.gif</image>
				<sortie index="4">SUD</sortie>
				<sortie index="6">OUEST</sortie>
		</zone>
		<zone index="6">
				<nom>Champs Agricoles</nom>
				<description> Des champs qui s'étendent à perte de vue. C'est ici que les paysans produisent les denrées vendues dans la galaxie entière.</description>
				<image>Maisonjoueur.gif</image>
				<sortie index="5">EST</sortie>
		</zone>
    </cartePlanete>
  </planete>
  <planete>
    <nom>Lorniala </nom>
    <description>Ancnciennement la planète la plus riche de la galaxie , Lorniala ne connait que le crime et la pauvreté depuis que la Mafia galactique a décidé de s'y installer.</description>
    <cartePlanete>
    	<zone index="7">
				<nom>Spatioport</nom>
				<description>  Un spatioport délabré surtout utilisé pour la contrebade.</description>
				<image>spatioport.jpg</image>
				<sortie index="0">SUD</sortie>
				<sortie index="8">NORD</sortie>
		</zone>
		<zone index="8">
				<nom>Marché</nom>
				<description>On trouve ce que l'on veut au marché de Lorniala. Pour le bon prix, on peut y acquérir les produits les plus illégaux. </description>
				<image>marcheSiGifOk.gif</image>
				<sortie index="7">SUD</sortie>
				<sortie index="9">OUEST</sortie>
		</zone>
		<zone index="9">
				<nom>Rue abandonnée</nom>
				<description>Cette rue déserte est bien pratique pour les criminels qui y exécutent leurs basses oeuvres.</description>
				<image>Maisonjoueur.gif</image>
				<sortie index="8">EST</sortie>
		</zone>
    </cartePlanete>
  </planete>*
  <planete>
    <nom>Kishu </nom>
    <description> Les moines de Kishu sont les gardiens d'une sagesse ancienne.</description>
    <cartePlanete>
    	<zone index="10">
				<nom>Spatioport</nom>
				<description> Le spatioport acceuille les pélerins de la galaxie entière venus y chercher l'apaisement de leur âme et la réponse à leurs questions spirituelles.</description>
				<image>vaisseau.png</image>
				<sortie index="0">SUD</sortie>
				<sortie index="11">NORD</sortie>
		</zone>
		<zone index="11">
				<nom>Jardins</nom>
				<description>Pélerins et moines viennent méditer dans ce magnifique jardin unique dans la galaxie.</description>
				<image>marcheSiGifOk.gif</image>
				<sortie index="10">SUD</sortie>
				<sortie index="12">OUEST</sortie>
		</zone>
		<zone index="12">
				<nom>Temple</nom>
				<description>Construit il y a des millénaires, ce temple isolé regorge de mystères.</description>
				<image>Maisonjoueur.gif</image>
				<sortie index="11">EST</sortie>
		</zone>
    </cartePlanete>
  </planete>
    <planete>
    <nom>Xénémos</nom>
    <description> Xénémos est une planète quittée par toute forme de vie à cause de son environnement volcanique instable. </description>
    <cartePlanete>
    	<zone index="13">
				<nom>Champ de bataille</nom>
				<description> Le lieu ou se déroule le combat final.</description>
				<image>vaisseau.png</image>
				<sortie index="0">SUD</sortie>
		</zone>
    </cartePlanete>
  </planete>
</espace>

=== ElodieFerreira/SpaceEnigmas/src/data/espace2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE espace SYSTEM "espace.dtd" >
<espace>
  <planete>
    <nom>nom
    	nom
    </nom>
    <description>description</description>
    <cartePlanete>
      <zone index="idvalue0">
        <nom>nom</nom>
        <description>description</description>
        <image>image</image>
        <sortie index="idvalue1">sortie</sortie>
      </zone>
    </cartePlanete>
  </planete>
  <planete>
  	<nom>nom</nom>
  	<description>description</description>
  	<cartePlanete>
  		<zone index="idvalue0">
  			<nom>nom</nom>
  			<description>description</description>
  			<image>image</image>
  			<sortie index="idvalue1">sortie</sortie>
  		</zone>
  		<zone index="idvalue0">
  			<nom>nom</nom>
  			<description>description</description>
  			<image>image</image>
  			<sortie index="idvalue1">sortie</sortie>
  		</zone>
  	</cartePlanete>
  </planete>
</espace>

=== ElodieFerreira/SpaceEnigmas/src/data/espace1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE espace SYSTEM "espace.dtd" >
<espace>
<!-- La sortie Index 0 correspond au vaisseau -->
  <planete>
    <nom>Perlimpinpin</nom>
    <description>Perlimpinpin est une planète isolée dans la galaxie. Ses habitants ne sont pas très importants.</description>
    <cartePlanete>
    	<zone index="1">
				<nom>Spatioport</nom>
				<description> Un spatioport peu fréquenté. Le seul moyen de sortir de la planète et de rejoindre le reste de la civilisation.</description>
				<image>vaisseau.png</image>
				<sortie index="0">SUD</sortie>
				<sortie index="2">NORD</sortie>
		</zone>
		<zone index="2">
				<nom>Perlimpinpin : Marché</nom>
				<description> Un petit marché local où les habitants se réunissent pour acheter aux marchands voyageurs des produits de toute la galaxie. </description>
				<image>marcheSiGifOk.gif</image>
				<sortie index="1">SUD</sortie>
				<sortie index="3">OUEST</sortie>
		</zone>
		<zone index="3">
				<nom>Maison de joueur</nom>
				<description> Une chambre typique, d'une maison ordinaire, sur une plan�te sans histoire...</description>
				<image>Maisonjoueur.gif</image>
				<sortie index="2">EST</sortie>
		</zone>
    </cartePlanete>
  </planete>
</espace>
